trigger:
  branches:
    include:
      - main

schedules:
  - cron: '0 */4 * * *'
    displayName: 'Check for new Docker image'
    branches:
      include:
        - main
    always: true

jobs:
  - job: CheckForNewDockerImage
    displayName: 'Check for new Docker image'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: PowerShell@2
        displayName: 'Check Dockerhub for new image'
        inputs:
          targetType: 'inline'
          script: |
            # Set Docker repository
            $DockerHubRepo = "$(DOCKER_HUB_USERNAME)/blazor-automated-email-marketing-system"
            # Log in to Dockerhub using service connection
            docker login -u $(DOCKER_HUB_USERNAME) -p $(DOCKER_HUB_PASSWORD)
            # Retrieve the latest Docker image
            docker pull $DockerHubRepo
            # Log out from Dockerhub
            docker logout
            # Check if a new image is found
            if (-not (docker images $DockerHubRepo --format "{{.Tag}}")) {
              Write-Host "No new Docker image found."
              exit 1
            }

# Job 2: Build, deploy and push Docker image to Dockerhub
  - job: BuildDeployAndPushToDockerHub
    displayName: 'Build, deploy, and push Docker image'
    steps:
      - task: Docker@2
        displayName: 'Pull Docker image'
        inputs:
          containerRegistry: 'docker-hub'
          repository: '$(DOCKER_HUB_USERNAME)/blazor-automated-email-marketing-system'
          command: 'pull'
          tags: 'latest'

      - script: |
          # Perform dotnet restore
          dotnet restore
          # Perform dotnet build
          dotnet build
        displayName: 'Restore and Build'

      # Perform Deployment test - check if rebuilt Docker image is valid
      - script: |
          if docker inspect $(DOCKER_HUB_USERNAME)/blazor-automated-email-marketing-system:latest &> /dev/null
          then
            echo "Deployment test passed. Docker image is valid."
          else
            echo "Deployment test failed. Invalid Docker image."
            exit 1
          fi
        displayName: 'Deployment Test'

      - task: Docker@2
        displayName: 'Push Docker image'
        inputs:
          containerRegistry: 'docker-hub'
          repository: '$(DOCKER_HUB_USERNAME)/blazor-automated-email-marketing-system-live'
          command: 'push'
          tags: 'latest'
