# Workflow for building and deploying the Blazor Automated Email Marketing System app
name: Build and Deploy

# Define triggers for the workflow
on:
  # Run workflow on push or pull request on main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Define jobs to be run in the workflow
jobs:
  # Build job - builds the Docker image and pushes it to Docker Hub
  build-and-push:
    runs-on: ubuntu-latest # Set the operating system for the job
    steps:
      # Check out the source code
      - uses: actions/checkout@v2
      # Build the Docker image and tag it with the version number
      - name: Build and tag Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 404bot/blazor-automated-email-marketing-system:v1.0
      # Get the SHA of the commit for use in the deployment step
      - name: Get commit SHA
        run: echo "::set-output name=commit_sha::$(git rev-parse HEAD)"
        id: commit_sha

  # Deploy job - deploys the app to the different environments
  deploy:
    needs: [build-and-push] # Ensure that the build job completes before starting deployment
    runs-on: ubuntu-latest # Set the operating system for the job
    strategy:
      matrix:
        environment: [development, staging, production] # Set up a matrix of environments to deploy to
    steps:
      # Check out the source code
      - uses: actions/checkout@v2
      # Pull the Docker image from Docker Hub
      - name: Pull Docker image
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # Set up environment variables based on the environment being deployed to
      - name: Set up environment variables
        run: |
          echo "ENVIRONMENT=${{ matrix.environment }}" >> $GITHUB_ENV
          case "${{ matrix.environment }}" in
            development)
              echo "URL=http://dev.myapp.com" >> $GITHUB_ENV
              ;;
            staging)
              echo "URL=http://test.myapp.com" >> $GITHUB_ENV
              ;;
            production)
              echo "URL=http://www.myapp.com" >> $GITHUB_ENV
              ;;
            *)
              echo "Invalid environment: ${{ matrix.environment }}" >&2
              exit 1
              ;;
          esac
      # Deploy the app using the Docker image and environment variables
      - name: Deploy to ${matrix.environment}
        run: |
          docker run --name blazor-app-${{ matrix.environment }} \
                     -e ASPNETCORE_ENVIRONMENT=${{ matrix.environment }} \
                     -e APP_URL=${{ env.URL }} \
                     -p 8080:80 \
                     -d 404bot/blazor-automated-email-marketing-system:v1.0
        env:
          DOCKER_IMAGE: 404bot/blazor-automated-email-marketing-system:v1.0
          COMMIT_SHA: ${{ needs.build-and-push.outputs.commit_sha }}
