# Workflow different environments (development, staging, production).
name: CI + CD pipeline

# Controls when the workflow will run
on:
  # On push or pull request on main
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Run workflow manually from actions tab
  workflow_dispatch:

# Jobs - sequentially or parallel
jobs:
  # Workflow contains a single job called "build"
  build:
    # Type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
      - name: Code_scanning
        run: echo Linting and scanning code
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0    
      - uses: actions/checkout@v3
      - name: Compile
        run: echo Compiling code
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
      - name: Test
        run: echo Testing code
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
      - name: ChecksComplete
        run: echo Checks complete code build successful

  # Deployment to development environment
  DeployDev:
    name: Deploy to development
    # Job to run only if the event is a pull request
    if: github.event.name == 'pull request'
    # The job needs the build job bto pass first
    needs: [ Build ]
    runs-on: ubuntu-latest
    # Define environmernt variables
    environment:
    # must match environments in repoasitory
        name: Development
        url: 'http//dev//myapp.com'
    steps:
        - name: Deploy
          run: echo Code deplyment to http://dev.myapp.com

    
  # Deployment to staging environment
  DeployStaging:
      name: Deploy to staging
      # Deploy only if committing  to main
      if: github.event.ref == 'refs/head/main'
      needs: [ Build ]
      runs-on: ubuntu-latest
      environment:
          name: Staging
          url: 'http://test/myapp.com'
      steps:
          - name: Deply
            run: echo Deploying to staging http://test.myapp.com


  # Deployment to production environment
  DeployProduction:
    name: Deploy to production
    needs: [ DeployStaging ]
    runs-on: ubuntu-latest
    environment:
        name: Production
        url: 'http://www.myapp.com'
    steps:
        - name: Deploy
          run: echo Deploying to production http:www.myapp.com
